# Introduction & Scenario
##### This case study explores the historical trip data of Cyclistic, a fictional bike-share company in Chicago. The objective is to understand how annual members (Subscribers) and casual riders (Customers) use Cyclistic bikes differently. These insights will help design a marketing strategy to convert casual riders into annual members, securing the company's future growth.

### Step 1 : Importing required libraries

In [149]:
import pandas as pd
from datetime import datetime

### Step 2 : Loading our datasets

In [150]:
q1 = pd.read_csv(r'C:\Users\platw\Downloads\Bike Scenario Case\Project\dataset\divvy_trips_2019\Divvy_Trips_2019_Q1.csv')
q2 = pd.read_csv(r'C:\Users\platw\Downloads\Bike Scenario Case\Project\dataset\divvy_trips_2019\Divvy_Trips_2019_Q2.csv')
q3 = pd.read_csv(r'C:\Users\platw\Downloads\Bike Scenario Case\Project\dataset\divvy_trips_2019\Divvy_Trips_2019_Q3.csv')   
q4 = pd.read_csv(r'C:\Users\platw\Downloads\Bike Scenario Case\Project\dataset\divvy_trips_2019\Divvy_Trips_2019_Q4.csv')

### Looking for compatible columns for combining them together.

In [151]:
print(q1.columns)
print(q2.columns)
print(q3.columns)
print(q4.columns)

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='str')
Index(['01 - Rental Details Rental ID', '01 - Rental Details Local Start Time',
       '01 - Rental Details Local End Time', '01 - Rental Details Bike ID',
       '01 - Rental Details Duration In Seconds Uncapped',
       '03 - Rental Start Station ID', '03 - Rental Start Station Name',
       '02 - Rental End Station ID', '02 - Rental End Station Name',
       'User Type', 'Member Gender',
       '05 - Member Details Member Birthday Year'],
      dtype='str')
Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='str')
Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='str')

## Step 3 : Transformation. 
### As we can see, I need to make some adjustments first!

In [152]:
q2.rename(columns=
          {'01 - Rental Details Rental ID': 'trip_id',
            '01 - Rental Details Local Start Time': 'start_time', 
            '01 - Rental Details Local End Time': 'end_time',
              '01 - Rental Details Bike ID': 'bikeid',
                '01 - Rental Details Duration In Seconds Uncapped': 'tripduration',
                  '03 - Rental Start Station ID': 'from_station_id', 
                  '03 - Rental Start Station Name': 'from_station_name',
                    '02 - Rental End Station ID': 'to_station_id', 
                    '02 - Rental End Station Name': 'to_station_name',
                      'User Type': 'usertype', 
                      'Member Gender': 'gender', 
                      '05 - Member Details Member Birthday Year': 'birthyear'}, inplace=True)

### Now I'm ready to concatenate them. After that, I will explore the dataset for duplicates, corrupt data, data types, etc.

In [153]:
df = pd.concat([q1, q2, q3, q4], ignore_index=True)

In [154]:
df.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,2167,390.0,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,4386,441.0,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,1524,829.0,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,252,"1,783.0",123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,1170,364.0,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0

In [155]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         str
 2   end_time           str
 3   bikeid             int64
 4   tripduration       str
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  gender             str
 11  birthyear          float64
dtypes: float64(1), int64(4), str(7)
memory usage: 349.5 MB

In [156]:
print(df.isna().sum())
print(df.isnull().sum())

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender               559206
birthyear            538751
dtype: int64
trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender               559206
birthyear            538751
dtype: int64

In [157]:
df.describe()

,trip_id,bikeid,from_station_id,to_station_id,birthyear
count,3.818004e+06,3.818004e+06,3.818004e+06,3.818004e+06,3.279253e+06
mean,2.391563e+07,3.380252e+03,2.016659e+02,2.026363e+02,1.984074e+03
std,1.212667e+06,1.902511e+03,1.560798e+02,1.562388e+02,1.086898e+01
min,2.174244e+07,1.000000e+00,1.000000e+00,1.000000e+00,1.759000e+03
25%,2.287379e+07,1.727000e+03,7.700000e+01,7.700000e+01,1.979000e+03
50%,2.396232e+07,3.451000e+03,1.740000e+02,1.740000e+02,1.987000e+03
75%,2.496370e+07,5.046000e+03,2.890000e+02,2.910000e+02,1.992000e+03
max,2.596290e+07,6.946000e+03,6.730000e+02,6.730000e+02,2.014000e+03

In [158]:
df.dtypes

trip_id                int64
start_time               str
end_time                 str
bikeid                 int64
tripduration             str
from_station_id        int64
from_station_name        str
to_station_id          int64
to_station_name          str
usertype                 str
gender                   str
birthyear            float64
dtype: object

In [159]:
df.duplicated().sum()

np.int64(0)

In [160]:
df['start_time'] = pd.to_datetime(df['start_time']).astype('datetime64[ns]')
df['end_time'] = pd.to_datetime(df['end_time']).astype('datetime64[ns]')

In [161]:
df.rename(columns={'tripduration': 'trip_duration_mins'}, inplace=True)

In [162]:
df['trip_duration_mins'] = df['trip_duration_mins'].astype(str).str.replace(',','').astype(float) / 60
df['trip_duration_mins'] = df['trip_duration_mins'].round(2)

In [163]:
df.head()

,trip_id,start_time,end_time,bikeid,trip_duration_mins,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,2167,6.50,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,4386,7.35,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,1524,13.82,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,252,29.72,123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,1170,6.07,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0

### Dropping unnecessary columns that have no impact on my analysis

In [164]:
df.drop(columns=['bikeid','from_station_id','to_station_id','gender','birthyear'], inplace=True)
df.columns

Index(['trip_id', 'start_time', 'end_time', 'trip_duration_mins',
       'from_station_name', 'to_station_name', 'usertype'],
      dtype='str')

In [165]:
df.loc[df['start_time'] > df['end_time']].count()

trip_id               13
start_time            13
end_time              13
trip_duration_mins    13
from_station_name     13
to_station_name       13
usertype              13
dtype: int64

#### Trips with invalid start and end time are excluded from the dataset.

In [166]:
df.drop(df[df['start_time'] > df['end_time']].index, inplace=True)

### Adding columns and changing necessary data types that I will need for visualization later on.

In [167]:
df['day_of_week'] = pd.to_datetime(df['start_time']).dt.dayofweek +1

In [168]:
df['name_of_day'] = pd.to_datetime(df['start_time']).dt.day_name()

In [169]:
df['month'] = pd.to_datetime(df['start_time']).dt.month_name()
df['month_number'] = pd.to_datetime(df['start_time']).dt.month

#### Optimize memory usage for categorical columns

In [170]:
df['usertype'] = df['usertype'].astype('category')

In [171]:
df.head()

,trip_id,start_time,end_time,trip_duration_mins,from_station_name,to_station_name,usertype,day_of_week,name_of_day,month,month_number
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,6.50,Wabash Ave & Grand Ave,Milwaukee Ave & Grand Ave,Subscriber,2,Tuesday,January,1
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,7.35,State St & Randolph St,Dearborn St & Van Buren St (*),Subscriber,2,Tuesday,January,1
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,13.82,Racine Ave & 18th St,Western Ave & Fillmore St (*),Subscriber,2,Tuesday,January,1
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,29.72,California Ave & Milwaukee Ave,Clark St & Elm St,Subscriber,2,Tuesday,January,1
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,6.07,Mies van der Rohe Way & Chicago Ave,Streeter Dr & Grand Ave,Subscriber,2,Tuesday,January,1

In [172]:
df['season'] = df['month'].map({'January': 'Winter', 'February': 'Winter', 'March': 'Spring', 'April': 'Spring', 'May': 'Spring', 'June': 'Summer', 'July': 'Summer', 'August': 'Summer', 'September': 'Fall', 'October': 'Fall', 'November': 'Fall', 'December': 'Winter'})

### Dropping any rows that are less than 1 minute and exceeding 1440 minutes (24 hours). In this case, we have 1,848 rows that are above 24 hours of use, which means that the users forgot to end their session or that the bikes have been stolen.

In [173]:
df.loc[df['trip_duration_mins'] > 1440].count()

trip_id               1848
start_time            1848
end_time              1848
trip_duration_mins    1848
from_station_name     1848
to_station_name       1848
usertype              1848
day_of_week           1848
name_of_day           1848
month                 1848
month_number          1848
season                1848
dtype: int64

In [174]:
df.loc[df['trip_duration_mins'] < 1].count()

trip_id               0
start_time            0
end_time              0
trip_duration_mins    0
from_station_name     0
to_station_name       0
usertype              0
day_of_week           0
name_of_day           0
month                 0
month_number          0
season                0
dtype: int64

In [175]:
df.drop(df[df['trip_duration_mins'] > 1440].index, inplace=True)

In [176]:
df.shape

(3816143, 12)

In [177]:
df.head()

,trip_id,start_time,end_time,trip_duration_mins,from_station_name,to_station_name,usertype,day_of_week,name_of_day,month,month_number,season
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,6.50,Wabash Ave & Grand Ave,Milwaukee Ave & Grand Ave,Subscriber,2,Tuesday,January,1,Winter
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,7.35,State St & Randolph St,Dearborn St & Van Buren St (*),Subscriber,2,Tuesday,January,1,Winter
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,13.82,Racine Ave & 18th St,Western Ave & Fillmore St (*),Subscriber,2,Tuesday,January,1,Winter
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,29.72,California Ave & Milwaukee Ave,Clark St & Elm St,Subscriber,2,Tuesday,January,1,Winter
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,6.07,Mies van der Rohe Way & Chicago Ave,Streeter Dr & Grand Ave,Subscriber,2,Tuesday,January,1,Winter

In [178]:
print(df['trip_duration_mins'].min())
print(df['trip_duration_mins'].max())

1.02
1440.0

In [179]:
df['hour_of_day'] = pd.to_datetime(df['start_time']).dt.hour

In [180]:
df.head()

,trip_id,start_time,end_time,trip_duration_mins,from_station_name,to_station_name,usertype,day_of_week,name_of_day,month,month_number,season,hour_of_day
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,6.50,Wabash Ave & Grand Ave,Milwaukee Ave & Grand Ave,Subscriber,2,Tuesday,January,1,Winter,0
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,7.35,State St & Randolph St,Dearborn St & Van Buren St (*),Subscriber,2,Tuesday,January,1,Winter,0
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,13.82,Racine Ave & 18th St,Western Ave & Fillmore St (*),Subscriber,2,Tuesday,January,1,Winter,0
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,29.72,California Ave & Milwaukee Ave,Clark St & Elm St,Subscriber,2,Tuesday,January,1,Winter,0
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,6.07,Mies van der Rohe Way & Chicago Ave,Streeter Dr & Grand Ave,Subscriber,2,Tuesday,January,1,Winter,0

## Step 4: Extract
### Our dataset is now ready for visualization.

In [ ]:
df.to_csv(r'C:\Users\platw\Downloads\Bike_Trips_2019\Experiment\Final\Bike_Trips_v6_2019.csv')

# AUTHOR
### KOUROUPIS PLATON
### 06/2026